### ISSUE TITLE
Price is not reducing when the VAT is 0

### ISSUE THREAD

**Issue by vladmirom** [vendidero/one-stop-shop-woocommerce#4]
Hi, we have a problem with the price re-calculation based on location. The store is in Finland and all the prices have the Finnish VAT applied to them, therefore, the prices are already with the VAT on EU territory. But for US we have 0% VAT, therefore the price should be reduced. We have that effect with the standard Woocommerce settings, however, when the plugin is activated, the price is not reducing. 

Is there anything in the settings that we have forgotten to enable? We followed the instruction here: https://vendidero.github.io/one-stop-shop-woocommerce/taxes. Or there's an issue somewhere in code?

<img width="1319" alt="Screenshot 1" src="https://user-images.githubusercontent.com/13310180/124443736-98921a00-dd86-11eb-8f0c-6054da7e9f09.png">
<img width="1253" alt="Screenshot 2" src="https://user-images.githubusercontent.com/13310180/124443741-9c25a100-dd86-11eb-809f-88b61fa6396c.png">

**Comment by dennisnissle** [comment]
Hi there,

this is due to WooCommerce not differentiating when enforcing gross prices, e.g. the gross price is used for third countries (which do not support VAT) too. We've created a little snippet for the functions.php to disable forcing gross prices in that specific case: https://gist.github.com/vendidero/56e0187b987dbaba3f4291e19cb7b2cd

Cheers

**Comment by vladmirom** [comment]
Lightning fast answer, thank you. The snippet works great!
